version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: se_nginx
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/symfony:cached

  mysql:
    image: mysql:8
    container_name: se_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: .docker/php
    container_name: se_php
    volumes:
      - .:/home/wwwroot/se
    environment:
      - maildev_host=se_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: se_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: se_maildev
    ports:
      - ${MAILDEV_PORT}:80